// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet.Net.Models;

#nullable disable

namespace Projet.Net.Migrations
{
    [DbContext(typeof(IitgamingContext))]
    [Migration("20231207134526_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projet.Net.Models.Equipe", b =>
                {
                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<string>("NomEquipe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("EquipeId")
                        .HasName("PK__Equipes__DC0A3743D8DD069C");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("Projet.Net.Models.Joueur", b =>
                {
                    b.Property<int>("JoueurId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<int?>("EquipeId")
                        .HasColumnType("int");

                    b.Property<string>("Pseudonyme")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("JoueurId")
                        .HasName("PK__Joueurs__D6CEE24011AFF52A");

                    b.HasIndex("EquipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Joueurs");
                });

            modelBuilder.Entity("Projet.Net.Models.Resultat", b =>
                {
                    b.Property<int>("ResultatId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateMatch")
                        .HasColumnType("date");

                    b.Property<int?>("EquipeGagnanteId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipePerdanteId")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreGagnant")
                        .HasColumnType("int");

                    b.Property<int?>("ScorePerdant")
                        .HasColumnType("int");

                    b.Property<int?>("TournoiId")
                        .HasColumnType("int");

                    b.HasKey("ResultatId")
                        .HasName("PK__Resultat__20BF3E6BA2D23FFE");

                    b.HasIndex("EquipeGagnanteId");

                    b.HasIndex("EquipePerdanteId");

                    b.HasIndex("TournoiId");

                    b.ToTable("Resultats");
                });

            modelBuilder.Entity("Projet.Net.Models.Tournoi", b =>
                {
                    b.Property<int>("TournoiId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("date");

                    b.Property<string>("Descr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Jeu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("jeu");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TournoiId")
                        .HasName("PK__Tournois__6536E3D97F53464F");

                    b.ToTable("Tournois");
                });

            modelBuilder.Entity("Projet.Net.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C811017D6");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Projet.Net.Models.Joueur", b =>
                {
                    b.HasOne("Projet.Net.Models.Equipe", "Equipe")
                        .WithMany("Joueurs")
                        .HasForeignKey("EquipeId")
                        .HasConstraintName("FK__Joueurs__EquipeI__6E01572D");

                    b.HasOne("Projet.Net.Models.User", "User")
                        .WithMany("Joueurs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Joueurs__UserId__6EF57B66");

                    b.Navigation("Equipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Projet.Net.Models.Resultat", b =>
                {
                    b.HasOne("Projet.Net.Models.Equipe", "EquipeGagnante")
                        .WithMany("ResultatEquipeGagnantes")
                        .HasForeignKey("EquipeGagnanteId")
                        .HasConstraintName("FK__Resultats__Equip__72C60C4A");

                    b.HasOne("Projet.Net.Models.Equipe", "EquipePerdante")
                        .WithMany("ResultatEquipePerdantes")
                        .HasForeignKey("EquipePerdanteId")
                        .HasConstraintName("FK__Resultats__Equip__73BA3083");

                    b.HasOne("Projet.Net.Models.Tournoi", "Tournoi")
                        .WithMany("Resultats")
                        .HasForeignKey("TournoiId")
                        .HasConstraintName("FK__Resultats__Tourn__71D1E811");

                    b.Navigation("EquipeGagnante");

                    b.Navigation("EquipePerdante");

                    b.Navigation("Tournoi");
                });

            modelBuilder.Entity("Projet.Net.Models.Equipe", b =>
                {
                    b.Navigation("Joueurs");

                    b.Navigation("ResultatEquipeGagnantes");

                    b.Navigation("ResultatEquipePerdantes");
                });

            modelBuilder.Entity("Projet.Net.Models.Tournoi", b =>
                {
                    b.Navigation("Resultats");
                });

            modelBuilder.Entity("Projet.Net.Models.User", b =>
                {
                    b.Navigation("Joueurs");
                });
#pragma warning restore 612, 618
        }
    }
}
